// Code generated by mockery. DO NOT EDIT.

package tenancy

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	tenancy "github.com/pablogore/ego/v4/tenancy"
)

// TenantResolver is an autogenerated mock type for the TenantResolver type
type TenantResolver struct {
	mock.Mock
}

type TenantResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *TenantResolver) EXPECT() *TenantResolver_Expecter {
	return &TenantResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx
func (_m *TenantResolver) Resolve(ctx context.Context) (tenancy.TenantContext, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 tenancy.TenantContext
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (tenancy.TenantContext, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) tenancy.TenantContext); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(tenancy.TenantContext)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TenantResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type TenantResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
func (_e *TenantResolver_Expecter) Resolve(ctx interface{}) *TenantResolver_Resolve_Call {
	return &TenantResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx)}
}

func (_c *TenantResolver_Resolve_Call) Run(run func(ctx context.Context)) *TenantResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *TenantResolver_Resolve_Call) Return(_a0 tenancy.TenantContext, _a1 error) *TenantResolver_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TenantResolver_Resolve_Call) RunAndReturn(run func(context.Context) (tenancy.TenantContext, error)) *TenantResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewTenantResolver creates a new instance of TenantResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTenantResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *TenantResolver {
	mock := &TenantResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
