apiVersion: v1
kind: ServiceAccount
metadata:
  name: urd-cluster
  namespace: urd-example
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: urd-cluster
  namespace: urd-example
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: urd-cluster
  namespace: urd-example
subjects:
  - kind: ServiceAccount
    name: urd-cluster
    namespace: urd-example
roleRef:
  kind: Role
  name: urd-cluster
  apiGroup: rbac.authorization.k8s.io
